openapi: 3.0.0
servers:
  - url: 'http://base.localhost.io'
info:
  description: >-
    The Base API.
  version: 1.0.0
  title: Base API
  contact:
    name: Amit Kshirsagar
tags:
  - name: base
    description: Base Service
paths:
  /base:
    get:
      security:
        - ApiKeyAuth: []
      tags:
        - base
      operationId: getBaseID
      summary: Get ID
      responses:
        200:
          $ref: '#/components/responses/success'
        400:
          $ref: '#/components/responses/404NotFound'

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorizationd

  responses:
    success:
      description: Get ID success
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Base'
    404NotFound:       # Can be referenced as '#/components/responses/404NotFound'
      description: The specified resource was not found.

    ImageResponse:     # Can be referenced as '#/components/responses/ImageResponse'
      description: An image.
      content:
        image/*:
          schema:
            type: string
            format: binary

    GenericError:      # Can be referenced as '#/components/responses/GenericError'
      description: An error occurred.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
        status:
          type: string
        correlation-id:
          type: string
    Base:
      type: object
      properties:
        id:
          type: string
          example: 1uu2g3g33