server:
  hostname: ${VHOSTNAME:${HOSTNAME:qa.local.k8cluster.io}}
  port: ${VPORT:2002}


spring:
  data:
    mongodb:
      host: ${VMONGODBHOST:mongodb.local.k8cluster.io}
      port: ${VMONGODBPORT:27017}
      database: ${VMONGODBDATA:k8cluster}
      repositories:
        type: AUTO
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    # excluded-view-names:
    # template-resolver-order:
    # view-names:

k8clusters:
  auth:
    apiV2Audience: ${AUTH_API_V2_AUDIENCE:https://k8cluster.auth0.com/api/v2/}
    callbackUrl: ${AUTH_API_V2_AUDIENCE:http://localhost:4200}
    clientId: ${AUTH_CLIENT_ID:AJn1FDdQtsuolZeU4MIK2O7NbXvjccKN}
    clientSecret: ${AUTH_CLIENT_SECRET:R40JLeatEu6mMUPAA25IyESgAjMmOUqE9LKI9gzWjejksoUJmoiZJaDzqublAFPw}
    domain: ${AUTH_DOMAIN:https://k8cluster.auth0.com}
    issuer: ${AUTH_ISSUER:https://k8cluster.auth0.com/}
    swaggerUser: ${SWAGGER_USER:user}
    swaggerUserPassword: ${SWAGGER_USER_PASS:Admin#1234}
    swaggerAdmin: ${SWAGGER_ADMIN:admin}
    swaggerAdminPassword: ${SWAGGER_ADMIN_PASS:Admin#1234}
    xmlFileName: ${VAUTHXML:defaultAuth-${spring.profiles.active}.xml}

swagger:
  title: QaService
  description: |
    Returns the list of the QA Items with given number of items in list. Currently, only has Math Operation Questions.
  version: 3.0
  contacts:
    name: Amit Kshirsagar
    email: amit.kshirsagar.13@gmail.com
    url: https://amitkshirsagar13.github.io/about