k8cluster:
  aws:
    region: eu-west-1
    credentialsClass: com.amazonaws.auth.profile.ProfileCredentialsProvider
#    credentialsClass: com.amazonaws.auth.InstanceProfileCredentialsProvider
  modules:
    dynamodb:
      integrative: true
      environmentPrefix: local
      development:
        hostName: localhost
        httpPort: 8000
        modelsPackage: io.k8clusters.base.modules.test.model