server:
  hostname: ${VHOSTNAME:${HOSTNAME:test.local.k8cluster.io}}
  port: ${VPORT:2002}


spring:
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    # excluded-view-names:
    # template-resolver-order:
    # view-names: